# 1. NUMPY BASICS

In [2]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
import numpy as np
# Let's define a one-dimensional array 
my_list = [1,2,3,4,5]

In [3]:
# Let's create a numpy array from the list "my_list"
x = np.array(my_list)
x

array([1, 2, 3, 4, 5])

In [4]:
type(x)

numpy.ndarray

In [5]:
# Multi-dimensional (Matrix definition) 
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

**MINI CHALLENGE #1:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [6]:
a = np.array([[4,6,8,7], 
[20,5,6,9]])
a

array([[ 4,  6,  8,  7],
       [20,  5,  6,  9]])

# 2. BUILT-IN METHODS AND FUNCTIONS 

In [7]:
# "rand()" uniform distribution between 0 and 1, the bracket contains dimension info
np.random.rand()
np.random.rand(5)

array([0.78900156, 0.27809134, 0.62642944, 0.38461449, 0.89151796])

In [8]:
# you can create a matrix of random number as well
np.random.rand(3,4)

array([[0.4334928 , 0.7242266 , 0.34343453, 0.54878603],
       [0.06869647, 0.04779481, 0.19511688, 0.27787814],
       [0.7689068 , 0.42101806, 0.44410188, 0.8156526 ]])

In [9]:
def one_d_scatter(array):
    import plotly.express as px
    fig = px.scatter(x=array, y=[0 for _ in array])
    fig.show()

def one_d_hist(array):
    import plotly.express as px
    fig = px.histogram(array)
    fig.show()


In [10]:
# "randn()" normal distribution between 0 and 1
randn_array = np.random.randn(1000)
one_d_scatter(randn_array)
one_d_hist(randn_array)

In [11]:
# "randint" is used to generate random integers between upper and lower bounds, not to up bound
[ np.random.randint(0,2) for _ in range(10)]

[0, 1, 1, 1, 1, 1, 1, 0, 1, 0]

In [12]:
# "randint" can be used to generate a certain number of random itegers as follows
np.random.randint(1,3,7)

array([2, 2, 2, 1, 2, 1, 1])

In [13]:
# np.arange creates an evenly spaced values within a given interval
np.arange(1,5)

array([1, 2, 3, 4])

In [14]:
# Create an evenly spaced values with a step of 5
np.arange(0,30,5)

array([ 0,  5, 10, 15, 20, 25])

In [15]:
# create a diagonal of ones and zeros everywhere else
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
# Array of ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
# Matrices of ones need one more layer of bracket
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
# Array of zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

**MINI CHALLENGE #2:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [19]:
def random_arr_create():
    x = input('give me a number')
    return np.random.randint(0, int(x) + 1, 20)

In [20]:
random_arr_create()

array([24, 40, 33, 41,  2,  8, 14, 45, 45, 29,  4, 32, 38, 17,  3,  5, 31,
       34,  1,  6])

# 3. SHAPE, LENGTH, TYPE, RESHAPE, AND MAX/MIN VALUES

In [21]:
# Let's define a one-dimensional array 
x = np.array([i for i in range(12)])

In [22]:
# Get Length of a numpy array
x.__len__()

12

In [23]:
# Get shape
x.shape

(12,)

In [24]:
# Obtain the datatype
x.dtype

dtype('int64')

In [25]:
# Reshape 1D array into a matrix
x = x.reshape(3,4)

In [26]:
# Obtain the maximum element (value)
x.max()

11

In [27]:
# Obtain the minimum element (value)
x.min()
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
# Obtain the location of the max element
np.where(x == x.max())

(array([2]), array([3]))

In [29]:
# Obtain the location of the min element
np.where(x == x.min())

(array([0]), array([0]))

In [30]:
print(x.argmax())
print(x.argmin())

11
0


**MINI CHALLENGE #3:**
- **Write a code that creates a 4x5 array inwhich numbers range between 300 and 500 such that the difference between elements is 10**

In [31]:
x = np.arange(300,500,10)
x = x.reshape(4,5)
x

array([[300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440],
       [450, 460, 470, 480, 490]])

**MINI CHALLENGE #4:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [32]:
x = np.random.randint(-1000,1000,(20,20))
# print(x)
print(x.max())
print(x.min())

996
-1000


# 4. MATHEMATICAL OPERATIONS

In [33]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
# Add 2 numpy arrays together
x + y

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
print(x*2)
print(x**2)
print(np.sqrt(x))
print(np.exp(x))

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  4  9 16 25 36 49 64 81]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


**MINI CHALLENGE #5:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```

In [37]:
X = [3, 20, 30]
Y = [4, 6, 7]
x, y = np.array(X), np.array(Y)

In [38]:
np.sqrt(sum((x - y)**2))

26.94438717061496

# 5. SLICING AND INDEXING 

In [39]:
x = np.arange(1,100,10)
x

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [40]:
# Access specific index from the numpy array
x[1]

11

In [41]:
# Starting from the first index 0 up until and NOT inlcluding the last element
x[:-1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81])

In [42]:
# Broadcasting, altering several values in a numpy array at once
# Doesn't work in List
x[:4] = 0
x

array([ 0,  0,  0,  0, 41, 51, 61, 71, 81, 91])

In [43]:
# Let's define a two dimensional numpy array
x = np.random.randint(0,12,(3,4))
x

array([[ 5,  6, 10, 10],
       [ 0,  0,  4, 10],
       [10,  7,  3, 10]])

In [44]:
# Get a row from a mtrix
x[2]

array([10,  7,  3, 10])

In [45]:
# Get one element
x[2][0]

10

**MINI CHALLENGE #6:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [46]:
x = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [47]:
x[-1] = -1
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [-1, -1, -1, -1, -1]])

In [48]:
x[:2, -2:] *= 2
x

array([[ 2, 30, 20, -4, -8],
       [ 3,  4, 40, -6, -4],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [-1, -1, -1, -1, -1]])

**MINI CHALLENGE #7:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [66]:
xx = np.array([[2, 30, 20, -2, -4],
    [3, 4, 40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])
xx

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [69]:
xx % 2 == 1

array([[False, False, False, False, False],
       [ True, False, False,  True, False],
       [ True, False, False, False, False],
       [ True,  True, False, False, False],
       [ True, False, False, False,  True]])

In [51]:
idxs = np.where(xx < 0)

In [52]:
for x, y in zip(idxs[0], idxs[1]):
    print(x, y)
    xx[x][y] = 0
xx

0 3
0 4
1 3
1 4
2 0
2 2


array([[ 2, 30, 20,  0,  0],
       [ 3,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [53]:
idx_odd = np.where(xx % 2 == 1)
idx_odd

(array([1, 3, 3, 4, 4]), array([0, 0, 1, 0, 4]))

In [54]:
for x, y in zip(idx_odd[0], idx_odd[1]):
    xx[x][y] = 25
xx

array([[ 2, 30, 20,  0,  0],
       [25,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [25, 25, 34, 22, 12],
       [25, 24, 22, 32, 25]])

# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

**MINI CHALLENGE #1 SOLUTION:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [55]:
x = np.array([[[4, 6, 8, 7] , [20, 5, 6, 9]]])
x

array([[[ 4,  6,  8,  7],
        [20,  5,  6,  9]]])

**MINI CHALLENGE #2 SOLUTION:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [56]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 20)
x

array([25, 43, 39, 10, 28, 27, 30,  1, 29, 43,  9, 20, 25,  9, 30, 12,  6,
       14,  7,  8])

**MINI CHALLENGE #3 SOLUTION:**
- **Write a code that creates a 4x5 array inwhich numbers ranging between 300 and 500 such that the difference between elements is 10**

In [57]:
x = np.arange(300, 500, 10)
x.shape

(20,)

In [58]:
x = x.reshape(4, 5)
print(x)

[[300 310 320 330 340]
 [350 360 370 380 390]
 [400 410 420 430 440]
 [450 460 470 480 490]]


**MINI CHALLENGE #4 SOLUTION:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [59]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

[[ 552 -743 -221 -397  -74 -306  134   94 -592 -598 -259  662 -406  620
    32 -410 -678  585 -476   19]
 [-873  -40  318 -580  165 -779 -803 -131 -703  591  999  720  309 -979
  -599  672  257 -871  -72 -319]
 [-217 -653 -436  523 -952   -8  409   75  857 -686  324 -483 -859  784
  -860 -785 -135  333  102  298]
 [ 121   95  535 -395 -906 -507 -927  484 -141 -370 -639 -109 -508  932
   267  -60  489   31    7  206]
 [-356  138  336 -298  126 -778 -558 -392  404  812  490  -72  706 -206
  -638 -319 -660 -815  205 -237]
 [-117  391  809 -320 -919  670 -323 -579  515  886 -693 -846  550  641
   125 -157  743 -277 -453   59]
 [ -62 -827  185  114 -576  336   13 -130 -218  423 -377  583  423   -9
  -913 -118 -794  550  695 -248]
 [-817  106  381  339  721 -505  800  448  954 -298 -925  220  -99  791
   503 -797 -517  406 -561  540]
 [-158 -769 -381  585 -541 -138 -341  804 -514 -641 -435  990 -539 -685
   637  -94 -595 -729 -959  289]
 [-641   28  812 -537    7 -395  304  430 -157  206 -46

**MINI CHALLENGE #5 SOLUTION:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```




In [60]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

array([ 5.        , 20.88061302, 30.8058436 ])

**MINI CHALLENGE #6 SOLUTION:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [61]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [62]:
X[4] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

In [63]:
X[:2, 3:]  = X[:2, 3:] * 2

In [64]:
X

array([[ 2, 30, 20, -4, -8],
       [ 3,  4, 40, -6, -4],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

**MINI CHALLENGE #7 SOLUTION:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [65]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X%2==1] = 25
X[X<0] = 0
X

array([[ 2, 30, 20,  0,  0],
       [25,  4, 40, 25,  0],
       [25,  4,  0, 90, 10],
       [25, 25, 34, 22, 12],
       [25, 24, 22, 32, 25]])